version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: oauth_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./db/mysql/init:/docker-entrypoint-initdb.d
      # - mysql_db:/var/lib/mysql
    networks:
      - local-bridge-mysql
  
  authorization_server:
    container_name: authorization_server
    build: ./authorization_server/
    ports:
      - 8080:8080
    networks:
      - local-bridge-mysql
    depends_on: 
      - mysql
  
  # protected_resource:
  #   container_name: protected_resource
  #   build: ./protected_resource/
  #   ports:
  #     - 8081:8080
  #   networks:
  #     - local-bridge-mysql
  #   depends_on: 
  #     - mysql

networks:
  local-bridge-mysql:
    driver: bridge
volumes:
  mysql_db:
    driver: local