version: '3.9'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: oauth_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./db/mysql/init:/docker-entrypoint-initdb.d
      # - mysql_db:/var/lib/mysql
    networks:
      - local-bridge-mysql
  
  authorization_server:
    container_name: authorization_server
    platform: linux/x86_64
    build: ./authorization_server/
    ports:
      - 80:80
    networks:
      - local-bridge-mysql
    depends_on: 
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=oauth_db
      - DB_USER=user
      - DB_PASSWORD=password
  
  # protected_resource:
  #   container_name: protected_resource
  #   build: ./protected_resource/
  #   ports:
  #     - 8081:8080
  #   networks:
  #     - local-bridge-mysql
  #   depends_on: 
  #     - mysql

networks:
  local-bridge-mysql:
    driver: bridge
volumes:
  mysql_db:
    driver: local