version: '3.9'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: oauth_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./db/mysql/init:/docker-entrypoint-initdb.d
      # - mysql_db:/var/lib/mysql
    networks:
      - local-bridge-mysql
  
  authorization_server:
    container_name: authorization_server
    platform: linux/x86_64
    build: ./authorization_server
    ports:
      - 8000:80
    networks:
      - local-bridge-mysql
    depends_on: 
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=oauth_db
      - DB_USER=user
      - DB_PASSWORD=password
  
  protected_resource:
    container_name: protected_resource
    build: ./protected_resource
    ports:
      - 8001:80
    networks:
      - local-bridge-mysql
    depends_on: 
      - mysql

  client:
    container_name: client
    platform: linux/x86_64
    build: ./client_application
    ports:
      - 8002:80
    networks:
      - local-client-bridge-mysql
    depends_on: 
      - client_mysql
    environment:
      - DB_HOST=client_mysql
      - DB_PORT=3306
      - DB_NAME=oauth_client_db
      - DB_USER=user
      - DB_PASSWORD=password
  
  client_mysql:
    image: mysql:8.0
    container_name: client_mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: oauth_client_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./db/mysql/init:/docker-entrypoint-initdb.d
      # - mysql_db:/var/lib/mysql
    networks:
      - local-client-bridge-mysql

networks:
  local-bridge-mysql:
    driver: bridge
  local-client-bridge-mysql:
    driver: bridge
volumes:
  mysql_db:
    driver: local