/*
 * This file is generated by jOOQ.
 */
package com.example.authorization_server.jooq;


import com.example.authorization_server.jooq.tables.Users;


/**
 * Convenience access to all tables in oauth_db.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>oauth_db.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
