/*
 * This file is generated by jOOQ.
 */
package com.example.authorization_server.jooq.tables.records;


import com.example.authorization_server.jooq.tables.Clients;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ClientsRecord extends UpdatableRecordImpl<ClientsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>oauth_db.clients.client_id</code>.
     */
    public void setClientId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>oauth_db.clients.client_id</code>.
     */
    public String getClientId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>oauth_db.clients.secret</code>.
     */
    public void setSecret(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>oauth_db.clients.secret</code>.
     */
    public String getSecret() {
        return (String) get(1);
    }

    /**
     * Setter for <code>oauth_db.clients.redirect_uri</code>.
     */
    public void setRedirectUri(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>oauth_db.clients.redirect_uri</code>.
     */
    public String getRedirectUri() {
        return (String) get(2);
    }

    /**
     * Setter for <code>oauth_db.clients.scope</code>.
     */
    public void setScope(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>oauth_db.clients.scope</code>.
     */
    public String getScope() {
        return (String) get(3);
    }

    /**
     * Setter for <code>oauth_db.clients.response_type</code>.
     */
    public void setResponseType(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>oauth_db.clients.response_type</code>.
     */
    public String getResponseType() {
        return (String) get(4);
    }

    /**
     * Setter for <code>oauth_db.clients.state</code>.
     */
    public void setState(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>oauth_db.clients.state</code>.
     */
    public String getState() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClientsRecord
     */
    public ClientsRecord() {
        super(Clients.CLIENTS);
    }

    /**
     * Create a detached, initialised ClientsRecord
     */
    public ClientsRecord(String clientId, String secret, String redirectUri, String scope, String responseType, String state) {
        super(Clients.CLIENTS);

        setClientId(clientId);
        setSecret(secret);
        setRedirectUri(redirectUri);
        setScope(scope);
        setResponseType(responseType);
        setState(state);
        resetChangedOnNotNull();
    }
}
