/*
 * This file is generated by jOOQ.
 */
package com.auth.client_application.jooq;


import com.auth.client_application.jooq.tables.Users;


/**
 * Convenience access to all tables in oauth_client_db.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>oauth_client_db.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
